version: '{build}'
platform: x64
cache:
  - c:\s
environment:
  GITHUB_TOKEN:
    secure: L/78Qw3wSosowhhilcm/u+wHOM97yiHdXgz8pbwRD3PQVtVSB1lZQ/BDaIm8RpsA
  STACK_ROOT: c:\s
  TMP: c:/tmp # https://github.com/haskell/cabal/issues/5386

install:
  - ps: curl -OutFile stack.zip -Uri https://github.com/commercialhaskell/stack/releases/download/v1.9.1/stack-1.9.1-windows-x86_64.zip
  - 7z x stack.zip stack.exe
build_script:
  - stack.exe setup
  - stack.exe --no-terminal build --only-dependencies
test_script:
  - stack.exe --no-terminal build --pedantic
  - stack.exe sdist
on_success:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG_NAME)
      {
        cp "$(./stack.exe path --local-install-root)/bin/github-release.exe" github-release.exe
        7z a github-release.zip github-release.exe
        ./github-release.exe upload --token $env:GITHUB_TOKEN --owner tfausak --repo github-release --tag $env:APPVEYOR_REPO_TAG_NAME --file github-release.zip --name github-release-windows.zip
      }
