name: github-release
version: 1.2.1

category: Utility
description: GitHub Release uploads files to GitHub releases.
github: tfausak/github-release
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: Upload files to GitHub releases.

dependencies:
  aeson: '>= 0.11.2 && < 0.12 || >= 1.0.2 && < 1.5'
  base: '>= 4.9.0 && < 4.12'
  bytestring: '>= 0.10.8 && < 0.11'
  http-client: '>= 0.4.31 && < 0.6'
  http-client-tls: '>= 0.2.4 && < 0.4'
  http-types: '>= 0.9.1 && < 0.13'
  mime-types: '>= 0.1.0 && < 0.2'
  optparse-generic: '>= 1.1.1 && < 1.4'
  text: '>= 1.2.2 && < 1.3'
  unordered-containers: '>= 0.2.7 && < 0.3'
  uri-templater: '>= 0.2.1 && < 0.4'
ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-safe
  - -Wno-unsafe

when:
  - condition: impl(ghc >= 8.4)
    ghc-options: -Wno-partial-fields

library:
  source-dirs: library

executable:
  dependencies:
    github-release: -any
  ghc-options:
    - -rtsopts
    - -threaded
  main: Main.hs
  source-dirs: executables
